services:
  reservas-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/reservas-app/data
      - ./templates:/reservas-app/templates 
    env_file:
      - .env
    networks:
      - reservas-net

networks:
  reservas-net:
    driver: bridge
